version: "3.9"
networks:
  default:
    driver: bridge

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microblog_app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo
      - redis
    environment:
      APP_ENV: ${APP_ENV}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./config/config-${APP_ENV}.yml:/config/config-${APP_ENV}.yml

volumes:
  mongo-data: