version: "3.9"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microblog_app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_ADDR=redis:6379
    depends_on:
      - mongo
      - redis
    restart: always

volumes:
  mongo-data: